### ISSUE TITLE
特征提取

### ISSUE THREAD

**Issue by Jahao26** [BladeDancer957/DualGATs#7]
您好，我已按照COSMIC代码提取相应的特征，另外使用了性能更好的语篇解析器。在IEMOCAP数据集中，大模型微调后精度不到50%，相应特征在完整模型DualGAT中精度不到60%，与您论文中提及的67%相差较大。请问您对COSMIC微调代码有没有修改，包括epoch，learn_rate？使用COSMIC微调后大模型精度是多少呢？

**Comment by BladeDancer957** [comment]
IEMOCAP数据集有两个版本，一个训练集有5810个utterance，另一个有6k+。后者相比于前者是更完整的对话，只不过其中一些utterance没有情感label，有label的utterance有5810个（因此后者统计时，也会按5810算），前者只保留了有label的部分。 没有label的utterance可以提供更全面完整的上下文信息。我这里用的后者。

**Comment by Jahao26** [comment]
> IEMOCAP数据集有两个版本，一个训练集有5810个utterance，另一个有6k+。后者相比于前者是更完整的对话，只不过其中一些utterance没有情感label，有label的utterance有5810个（因此后者统计时，也会按5810算），前者只保留了有label的部分。 没有label的utterance可以提供更全面完整的上下文信息。我这里用的后者。

谢谢您的解答！

**Comment by JYueqi** [comment]
您好，请问您做特征提取时是完全按照COSMIC的代码做的吗？请问您对COSMIC代码中的 `roberta1, roberta2, roberta3, roberta4`这4层特征是如何处理的呢？另外还想请问DualGATs 中 dataset.py代码中 `self.links`这个是什么特征呢？

**Comment by Jahao26** [comment]
> 您好，请问您做特征提取时是完全按照COSMIC的代码做的吗？请问您对COSMIC代码中的 `roberta1, roberta2, roberta3, roberta4`这4层特征是如何处理的呢？另外还想请问DualGATs 中 dataset.py代码中 `self.links`这个是什么特征呢？

1. 完全按照COSMIC代码运行，但如果需要跑到接近SOTA，需要调整参数；
2. roberta1/2/3/4 分别是倒数4层的特征，我只取倒数第一层；
3. self.links是序列对数组，例如[(1,2), (4,5)]表示u1和u2，u4和u5之间存在连接

**Comment by JYueqi** [comment]
十分感谢！

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月26日 11:39 |
| 收件人 | BladeDancer957/DualGATs ***@***.***> |
| 抄送人 | MoonBlue ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [BladeDancer957/DualGATs] 特征提取 (Issue #7) |

您好，请问您做特征提取时是完全按照COSMIC的代码做的吗？请问您对COSMIC代码中的 roberta1, roberta2, roberta3, roberta4这4层特征是如何处理的呢？另外还想请问DualGATs 中 dataset.py代码中 self.links这个是什么特征呢？

完全按照COSMIC代码运行，但如果需要跑到接近SOTA，需要调整参数；
roberta1/2/3/4 分别是倒数4层的特征，我只取倒数第一层；
self.links是序列对数组，例如[(1,2), (4,5)]表示u1和u2，u4和u5之间存在连接

**Comment by Keminae** [comment]
您好，请问您使用的是哪个语篇解析器，可以分享一下吗
