### ISSUE TITLE
关于特征处理的代码

### ISSUE THREAD

**Issue by JYueqi** [BladeDancer957/DualGATs#8]
您好，我对于 `self.videoSpeakers, self.videoLabels, roberta_feature, \
            self.links, self.relations, self.videoSentence, self.trainVid, self.testVid, self.validVid = read_pickle('./data/IEMOCAP_Features.pkl')` 这一段代码不是很理解其中 `self.links, self.relations`的含义，以及关于 ` roberta_feature` 是指 COSMIC代码中 4层特征的拼接 还是您使用了某一层特征呢？ 希望能得到您的解答，谢谢

**Comment by JYueqi** [comment]
我阅读了一些DDP源码，请问links和relations是DDP任务中的概念吗

**Comment by BladeDancer957** [comment]
> 您好，我对于 `self.videoSpeakers, self.videoLabels, roberta_feature, \ self.links, self.relations, self.videoSentence, self.trainVid, self.testVid, self.validVid = read_pickle('./data/IEMOCAP_Features.pkl')` 这一段代码不是很理解其中 `self.links, self.relations`的含义，以及关于 ` roberta_feature` 是指 COSMIC代码中 4层特征的拼接 还是您使用了某一层特征呢？ 希望能得到您的解答，谢谢

1.  某一层的特征
2.  self.links指的是两个utterance之间是否有连接，值为0或1；self.relations指的是两个utterance之间的连接是什么类型，关系类型的索引id。
